version: 3.2.47

services:
  web-app:
    container_name: Django
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./service:/service
    environment:
      - DB_HOST=database
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DB_PASS=pass
    command: >
      sh -c
      "python manage.py makemigrations
      &&
      python manage.py migrate
      &&
      python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - database
  
  database:
    container_name: Postgres
    image: postgres:14-alpine3.17
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=pass

  vue:
    container_name: Vue
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    volumes:
      - ./frontend/:/app
    command: >
      sh -c "npm run serve -- --port 8081"
    ports:
      - '8081:8081'
    depends_on:
      - web-app